function y = band_pass_filter(x, fs, start_freq, end_freq)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 02-Oct-2020 09:28:04

Fs = fs; %1/mean(diff(tx)); % Average sample rate
y = bandpass(x,[start_freq end_freq],Fs,'Steepness',0.85,'StopbandAttenuation',60);
y = bandpass(y,[start_freq end_freq],Fs,'Steepness',0.85,'StopbandAttenuation',60);
