function [fitresult, gof] = createFit(dus)
%CREATEFIT(DUS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: dus
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Sep-2020 13:12:50


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], dus );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'dus', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'dus', 'Interpreter', 'none' );
grid on


