function y = envelop_to_cut(x,tx)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 07-Oct-2020 11:33:14

[y,~] = envelope(x);
y = smoothdata(y,'movmean',0.05,'SamplePoints',tx);
