function [fitresult, gof] = fit_exp(t, test_peak,x_fit, y_fit)
%CREATEFIT1(T,TEST_PEAK)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: test_peak
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Oct-2020 17:09:31


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, test_peak );

% Set up fittype and options.
%ft = fittype( 'exp1' );
ft = @(a,x)y_fit*exp(a*(x-x_fit));
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Startpoint = 1;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




