function y = preprocess_envelope(x)
%  Preprocess input x
%    This function expects an input vector x.

% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 24-Sep-2020 00:54:03
separation_hz = 25;
maxima_separation_samples = (1/separation_hz) * 187 * 0.3; 
maximaSeparation = ceil(maxima_separation_samples);
[y,~] = envelope(x,maximaSeparation,'peak');
