function y = preprocess(x,tx)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 02-Oct-2020 14:18:28

Fs = 1/mean(diff(tx)); % Average sample rate
y = lowpass(x,25,Fs,'Steepness',0.95,'StopbandAttenuation',80);
y = lowpass(y,25,Fs,'Steepness',0.95,'StopbandAttenuation',80);
y = highpass(y,6,Fs,'Steepness',0.95,'StopbandAttenuation',60);
y = highpass(y,6,Fs,'Steepness',0.95,'StopbandAttenuation',60);
