function y = preprocess_band_pass(x,tx, low_limit, up_limit)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 24-Sep-2020 00:36:59

Fs = 1/mean(diff(tx)); % Average sample rate
y = bandpass(x,[low_limit up_limit],Fs,'Steepness',0.75,'StopbandAttenuation',60);
%y = bandpass(y,[6.5 8.5],Fs,'Steepness',0.85,'StopbandAttenuation',60);
